# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://elliehamilton3.github.io
title: Portfolio
email: eleanorhamilton77@gmail.com
author: Ellie Hamilton
description: > # "Write an awesome description for your new site here.
  You can edit this line in _config.yml. It will appear in your document
  head meta (for Google search results) and in your feed.xml site
  description.
copyright: 'Copyright &copy; 2017 Ellie Hamilton. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/3llieHamilton
  - title: github
    url: https://github.com/elliehamilton3
  - title: linkedin
    url: https://www.linkedin.com/in/3lliehamilton/
  - title: stack-overflow
    url: https://stackoverflow.com/users/story/7980790
  - title: envelope
    url: mailto:eleanorhamilton77@gmail.com?Subject=Website%20Enquiry
